version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    container_name: be-prod
    environment:
      - ./backend/.env.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    container_name: fe-prod
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
